-- Reverb storefront clean baseline v1 (covers migrations 0001-0018)
-- Generated by: npm run baseline:build
-- Run once in the Supabase SQL Editor on a new, empty project.
-- This file contains no catalog, branding, legal copy, or credentials.

begin;

select pg_advisory_xact_lock(hashtext('reverb-storefront-clean-baseline-v1'));

do $$
begin
  if to_regclass('public.site_settings') is not null then
    raise exception 'Baseline refused: this project already contains storefront tables';
  end if;
  if exists (select 1 from auth.users limit 1) then
    raise exception 'Baseline refused: create the first administrator only after the baseline succeeds';
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 0001_schema.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0001 schema
-- Core tables for storefront + merchant panel.
-- Postgres / Supabase. Run in order 0001..0005.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
  create type user_role as enum ('admin', 'editor', 'viewer');
exception when duplicate_object then null; end $$;

do $$ begin
  create type order_status as enum (
    'pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'
  );
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- Profiles (mirrors auth.users, holds role)
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text,
  role        user_role not null default 'viewer',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------
create table if not exists public.categories (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  slug        text not null unique,
  description text,
  image_path  text,
  sort        int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.products (
  id             uuid primary key default gen_random_uuid(),
  title          text not null,
  slug           text not null unique,
  original_price numeric(12,2) not null default 0,
  current_price  numeric(12,2) not null default 0,
  description    jsonb,                       -- { "html": "<p>..</p>" }
  status         text not null default 'active', -- active | draft | archived
  product_type   text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists products_status_idx on public.products (status);

create table if not exists public.product_images (
  id         uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  path       text not null,
  alt        text,
  is_main    boolean not null default false,
  sort       int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists product_images_product_idx on public.product_images (product_id);

create table if not exists public.product_variants (
  id                  uuid primary key default gen_random_uuid(),
  product_id          uuid not null references public.products (id) on delete cascade,
  size                text,
  color               text,
  sku                 text,
  price_override      numeric(12,2),
  stock_quantity      int not null default 0,
  low_stock_threshold int not null default 5,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (product_id, size, color)
);
create index if not exists product_variants_product_idx on public.product_variants (product_id);

create table if not exists public.product_categories (
  product_id  uuid not null references public.products (id) on delete cascade,
  category_id uuid not null references public.categories (id) on delete cascade,
  primary key (product_id, category_id)
);

-- ---------------------------------------------------------------------------
-- Customers + orders
-- ---------------------------------------------------------------------------
create table if not exists public.customers (
  id           uuid primary key default gen_random_uuid(),
  name         text,
  phone        text unique,
  email        text,
  address      jsonb,
  orders_count int not null default 0,
  total_spent  numeric(12,2) not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create sequence if not exists order_number_seq start 1001;

create table if not exists public.orders (
  id             uuid primary key default gen_random_uuid(),
  order_number   text not null unique default ('VE-' || nextval('order_number_seq')::text),
  status         order_status not null default 'pending',
  customer_id    uuid references public.customers (id) on delete set null,
  delivery       jsonb not null,   -- { country, firstName, lastName, address, city, postalCode, phone }
  totals         jsonb not null,   -- { subtotal, shipping, total }
  payment_method text not null default 'cod',
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_customer_idx on public.orders (customer_id);
create index if not exists orders_created_idx on public.orders (created_at desc);

create table if not exists public.order_items (
  id         uuid primary key default gen_random_uuid(),
  order_id   uuid not null references public.orders (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  variant_id uuid references public.product_variants (id) on delete set null,
  title      text,          -- snapshot of product title at purchase time
  size       text,
  color      text,
  quantity   int not null default 1,
  unit_price numeric(12,2) not null default 0
);
create index if not exists order_items_order_idx on public.order_items (order_id);

-- ---------------------------------------------------------------------------
-- Content
-- ---------------------------------------------------------------------------
create table if not exists public.promotions (
  id               uuid primary key default gen_random_uuid(),
  title            text not null,
  description      text,
  image_path       text,
  discount_percent numeric(5,2),
  active           boolean not null default true,
  starts_at        timestamptz,
  ends_at          timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table if not exists public.reviews (
  id            uuid primary key default gen_random_uuid(),
  customer_name text,
  image_path    text,
  rating        int check (rating between 1 and 5),
  body          text,
  product_id    uuid references public.products (id) on delete set null,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now()
);

create table if not exists public.contact_submissions (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  email        text not null,
  phone        text,
  message      text not null,
  is_read      boolean not null default false,
  submitted_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Settings + operations
-- ---------------------------------------------------------------------------
create table if not exists public.site_settings (
  id                     int primary key default 1 check (id = 1),
  store_name             text not null default 'VE-gear',
  logo_path              text,
  contact_email          text,
  contact_phone          text,
  address                text,
  currency               text not null default 'USD',
  currency_symbol        text not null default '$',
  shipping_flat          numeric(12,2) not null default 0,
  free_shipping_threshold numeric(12,2),
  socials                jsonb not null default '{}'::jsonb,
  google_analytics_id    text,
  meta_pixel_id          text,
  gtm_id                 text,
  analytics_enabled      boolean not null default false,
  security_enabled       boolean not null default false,
  updated_at             timestamptz not null default now()
);

create table if not exists public.blocked_ips (
  id         uuid primary key default gen_random_uuid(),
  ip         text not null unique,
  reason     text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 0002_functions_triggers.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0002 functions & triggers

-- ---------------------------------------------------------------------------
-- Role helpers (used by RLS). SECURITY DEFINER so policies can read profiles
-- without recursive RLS checks.
-- ---------------------------------------------------------------------------
create or replace function public.current_role()
returns user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()) = 'admin', false);
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select role from public.profiles where id = auth.uid()) in ('admin', 'editor'),
    false
  );
$$;

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'profiles','categories','products','product_variants','customers',
    'orders','promotions','site_settings'
  ] loop
    execute format(
      'drop trigger if exists trg_touch_%1$s on public.%1$s;
       create trigger trg_touch_%1$s before update on public.%1$s
         for each row execute function public.touch_updated_at();', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- New auth user -> profile. First ever user becomes admin, rest viewer.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  assigned user_role;
begin
  if not exists (select 1 from public.profiles) then
    assigned := 'admin';
  else
    assigned := 'viewer';
  end if;

  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    assigned
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Customer upsert + aggregates driven from orders
-- ---------------------------------------------------------------------------
create or replace function public.resolve_order_customer()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_phone text := nullif(trim(new.delivery ->> 'phone'), '');
  v_name  text := trim(coalesce(new.delivery ->> 'firstName','') || ' ' || coalesce(new.delivery ->> 'lastName',''));
  v_customer_id uuid;
begin
  if new.customer_id is not null then
    return new;
  end if;

  if v_phone is null then
    return new; -- no phone, cannot dedupe; leave customer_id null
  end if;

  select id into v_customer_id from public.customers where phone = v_phone;

  if v_customer_id is null then
    insert into public.customers (name, phone, address)
    values (nullif(v_name,''), v_phone, new.delivery)
    returning id into v_customer_id;
  else
    update public.customers
      set name = coalesce(nullif(v_name,''), name),
          address = new.delivery,
          updated_at = now()
      where id = v_customer_id;
  end if;

  new.customer_id := v_customer_id;
  return new;
end;
$$;

drop trigger if exists trg_resolve_order_customer on public.orders;
create trigger trg_resolve_order_customer
  before insert on public.orders
  for each row execute function public.resolve_order_customer();

create or replace function public.recompute_customer_totals(p_customer_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.customers c set
    orders_count = coalesce(agg.cnt, 0),
    total_spent  = coalesce(agg.spent, 0),
    updated_at   = now()
  from (
    select
      count(*) filter (where status <> 'cancelled') as cnt,
      sum((totals ->> 'total')::numeric) filter (where status <> 'cancelled') as spent
    from public.orders
    where customer_id = p_customer_id
  ) agg
  where c.id = p_customer_id;
$$;

create or replace function public.after_order_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    if old.customer_id is not null then
      perform public.recompute_customer_totals(old.customer_id);
    end if;
    return old;
  end if;

  if new.customer_id is not null then
    perform public.recompute_customer_totals(new.customer_id);
  end if;
  if tg_op = 'UPDATE' and old.customer_id is distinct from new.customer_id
     and old.customer_id is not null then
    perform public.recompute_customer_totals(old.customer_id);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_after_order_change on public.orders;
create trigger trg_after_order_change
  after insert or update or delete on public.orders
  for each row execute function public.after_order_change();

-- ---------------------------------------------------------------------------
-- place_order RPC: atomic order + items, customer handled by trigger above.
-- Callable by anon (storefront checkout). SECURITY DEFINER bypasses RLS.
-- payload:
--   { delivery:{...}, items:[{product_id,variant_id,size,color,quantity,unit_price,title}],
--     totals:{subtotal,shipping,total}, notes }
-- ---------------------------------------------------------------------------
create or replace function public.place_order(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_order_number text;
  item jsonb;
begin
  if payload -> 'delivery' is null or payload -> 'items' is null or payload -> 'totals' is null then
    raise exception 'delivery, items and totals are required';
  end if;

  insert into public.orders (delivery, totals, notes)
  values (payload -> 'delivery', payload -> 'totals', nullif(payload ->> 'notes',''))
  returning id, order_number into v_order_id, v_order_number;

  for item in select * from jsonb_array_elements(payload -> 'items') loop
    insert into public.order_items
      (order_id, product_id, variant_id, title, size, color, quantity, unit_price)
    values (
      v_order_id,
      nullif(item ->> 'product_id','')::uuid,
      nullif(item ->> 'variant_id','')::uuid,
      item ->> 'title',
      item ->> 'size',
      item ->> 'color',
      coalesce((item ->> 'quantity')::int, 1),
      coalesce((item ->> 'unit_price')::numeric, 0)
    );

    -- decrement stock if a variant was specified
    if nullif(item ->> 'variant_id','') is not null then
      update public.product_variants
        set stock_quantity = greatest(0, stock_quantity - coalesce((item ->> 'quantity')::int, 1))
        where id = (item ->> 'variant_id')::uuid;
    end if;
  end loop;

  return jsonb_build_object('id', v_order_id, 'order_number', v_order_number);
end;
$$;

grant execute on function public.place_order(jsonb) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 0003_rls.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0003 row level security
-- Model:
--   public (anon) : read published storefront data; insert contact submissions.
--   staff (admin/editor) : full CRUD on catalog/orders/content.
--   admin : users/roles + settings + blocked_ips.
--   orders/order_items are written only through place_order() (SECURITY DEFINER),
--     so no anon insert policy is needed there.

alter table public.profiles            enable row level security;
alter table public.categories          enable row level security;
alter table public.products            enable row level security;
alter table public.product_images      enable row level security;
alter table public.product_variants    enable row level security;
alter table public.product_categories  enable row level security;
alter table public.customers           enable row level security;
alter table public.orders              enable row level security;
alter table public.order_items         enable row level security;
alter table public.promotions          enable row level security;
alter table public.reviews             enable row level security;
alter table public.contact_submissions enable row level security;
alter table public.site_settings       enable row level security;
alter table public.blocked_ips         enable row level security;

-- helper to (re)create a policy idempotently
-- (Postgres has no "create policy if not exists"; drop first.)

-- ---- profiles ----
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles
  for select using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles
  for update using (id = auth.uid())
  with check (id = auth.uid() and role = (select role from public.profiles where id = auth.uid()));

-- ---- categories ----
drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select using (true);
drop policy if exists categories_staff_write on public.categories;
create policy categories_staff_write on public.categories
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- products ----
drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products
  for select using (status = 'active' or public.is_staff());
drop policy if exists products_staff_write on public.products;
create policy products_staff_write on public.products
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- product_images ----
drop policy if exists product_images_public_read on public.product_images;
create policy product_images_public_read on public.product_images for select using (true);
drop policy if exists product_images_staff_write on public.product_images;
create policy product_images_staff_write on public.product_images
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- product_variants ----
drop policy if exists product_variants_public_read on public.product_variants;
create policy product_variants_public_read on public.product_variants for select using (true);
drop policy if exists product_variants_staff_write on public.product_variants;
create policy product_variants_staff_write on public.product_variants
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- product_categories ----
drop policy if exists product_categories_public_read on public.product_categories;
create policy product_categories_public_read on public.product_categories for select using (true);
drop policy if exists product_categories_staff_write on public.product_categories;
create policy product_categories_staff_write on public.product_categories
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- customers (staff only; storefront never reads these) ----
drop policy if exists customers_staff_read on public.customers;
create policy customers_staff_read on public.customers for select using (public.is_staff());
drop policy if exists customers_staff_write on public.customers;
create policy customers_staff_write on public.customers
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- orders (staff manage; storefront writes via place_order RPC) ----
drop policy if exists orders_staff_read on public.orders;
create policy orders_staff_read on public.orders for select using (public.is_staff());
drop policy if exists orders_staff_write on public.orders;
create policy orders_staff_write on public.orders
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- order_items ----
drop policy if exists order_items_staff_read on public.order_items;
create policy order_items_staff_read on public.order_items for select using (public.is_staff());
drop policy if exists order_items_staff_write on public.order_items;
create policy order_items_staff_write on public.order_items
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- promotions ----
drop policy if exists promotions_public_read on public.promotions;
create policy promotions_public_read on public.promotions
  for select using (active or public.is_staff());
drop policy if exists promotions_staff_write on public.promotions;
create policy promotions_staff_write on public.promotions
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- reviews ----
drop policy if exists reviews_public_read on public.reviews;
create policy reviews_public_read on public.reviews
  for select using (is_published or public.is_staff());
drop policy if exists reviews_staff_write on public.reviews;
create policy reviews_staff_write on public.reviews
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- contact_submissions (anyone may submit; staff read/manage) ----
drop policy if exists contact_public_insert on public.contact_submissions;
create policy contact_public_insert on public.contact_submissions
  for insert with check (true);
drop policy if exists contact_staff_read on public.contact_submissions;
create policy contact_staff_read on public.contact_submissions
  for select using (public.is_staff());
drop policy if exists contact_staff_write on public.contact_submissions;
create policy contact_staff_write on public.contact_submissions
  for all using (public.is_staff()) with check (public.is_staff());

-- ---- site_settings (public read for storefront branding/analytics; admin write) ----
drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings for select using (true);
drop policy if exists site_settings_admin_write on public.site_settings;
create policy site_settings_admin_write on public.site_settings
  for all using (public.is_admin()) with check (public.is_admin());

-- ---- blocked_ips (admin only) ----
drop policy if exists blocked_ips_admin_all on public.blocked_ips;
create policy blocked_ips_admin_all on public.blocked_ips
  for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists blocked_ips_staff_read on public.blocked_ips;
create policy blocked_ips_staff_read on public.blocked_ips
  for select using (public.is_staff());

-- ---------------------------------------------------------------------------
-- 0004_storage.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0004 storage buckets & policies
-- Public read; writes restricted to staff (admin/editor).

insert into storage.buckets (id, name, public)
values
  ('product-images',   'product-images',   true),
  ('category-images',  'category-images',  true),
  ('review-images',    'review-images',    true),
  ('promotion-images', 'promotion-images', true),
  ('branding',         'branding',         true)
on conflict (id) do nothing;

-- Public read for every VE-gear bucket
drop policy if exists "vegear public read" on storage.objects;
create policy "vegear public read" on storage.objects
  for select using (
    bucket_id in ('product-images','category-images','review-images','promotion-images','branding')
  );

-- Staff insert
drop policy if exists "vegear staff insert" on storage.objects;
create policy "vegear staff insert" on storage.objects
  for insert to authenticated
  with check (
    bucket_id in ('product-images','category-images','review-images','promotion-images','branding')
    and public.is_staff()
  );

-- Staff update
drop policy if exists "vegear staff update" on storage.objects;
create policy "vegear staff update" on storage.objects
  for update to authenticated
  using (
    bucket_id in ('product-images','category-images','review-images','promotion-images','branding')
    and public.is_staff()
  )
  with check (
    bucket_id in ('product-images','category-images','review-images','promotion-images','branding')
    and public.is_staff()
  );

-- Staff delete
drop policy if exists "vegear staff delete" on storage.objects;
create policy "vegear staff delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id in ('product-images','category-images','review-images','promotion-images','branding')
    and public.is_staff()
  );

-- ---------------------------------------------------------------------------
-- 0005_seed.sql
-- ---------------------------------------------------------------------------
-- Clean required bootstrap; intentionally excludes demo catalog data.
insert into public.site_settings
  (id, store_name, currency, currency_symbol, contact_email, shipping_flat, free_shipping_threshold)
values (1, 'Store', 'USD', '$', null, 0, null)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 0006_cms.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0006 CMS layer (hero banners + homepage sections + announcement bar)
-- Makes the storefront homepage fully admin-managed. Sections/banners are
-- read publicly only when active; the storefront hides anything with no data.

-- =========================================================================
-- Tables
-- =========================================================================

-- Hero banners / slides shown at the top of the homepage.
create table if not exists public.banners (
  id                uuid primary key default gen_random_uuid(),
  title             text,
  subtitle          text,
  image_path        text not null,
  mobile_image_path text,
  cta_label         text,
  cta_url           text,
  sort              int not null default 0,
  active            boolean not null default true,
  starts_at         timestamptz,
  ends_at           timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists banners_active_sort_idx on public.banners (active, sort);

-- Ordered, toggleable homepage sections. `type` maps to a storefront renderer;
-- `config` carries optional per-section settings (e.g. product limit).
create table if not exists public.homepage_sections (
  id         uuid primary key default gen_random_uuid(),
  type       text not null check (
                type in ('hero','categories','featured','reviews','promo','richtext')
             ),
  title      text,
  subtitle   text,
  body       text,
  sort       int not null default 0,
  active     boolean not null default true,
  config     jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists homepage_sections_active_sort_idx
  on public.homepage_sections (active, sort);

-- Announcement bar fields on the singleton site_settings row.
alter table public.site_settings
  add column if not exists announcement_text   text,
  add column if not exists announcement_active boolean not null default false,
  add column if not exists announcement_url    text;

-- =========================================================================
-- updated_at triggers (touch_updated_at defined in 0002)
-- =========================================================================

drop trigger if exists trg_banners_touch on public.banners;
create trigger trg_banners_touch before update on public.banners
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_homepage_sections_touch on public.homepage_sections;
create trigger trg_homepage_sections_touch before update on public.homepage_sections
  for each row execute function public.touch_updated_at();

-- =========================================================================
-- Row level security
-- =========================================================================

alter table public.banners           enable row level security;
alter table public.homepage_sections enable row level security;

-- banners: public reads only active (and inside schedule window); staff full CRUD.
drop policy if exists banners_public_read on public.banners;
create policy banners_public_read on public.banners
  for select using (
    public.is_staff()
    or (
      active
      and (starts_at is null or starts_at <= now())
      and (ends_at is null or ends_at >= now())
    )
  );
drop policy if exists banners_staff_write on public.banners;
create policy banners_staff_write on public.banners
  for all using (public.is_staff()) with check (public.is_staff());

-- homepage_sections: public reads active; staff full CRUD.
drop policy if exists homepage_sections_public_read on public.homepage_sections;
create policy homepage_sections_public_read on public.homepage_sections
  for select using (active or public.is_staff());
drop policy if exists homepage_sections_staff_write on public.homepage_sections;
create policy homepage_sections_staff_write on public.homepage_sections
  for all using (public.is_staff()) with check (public.is_staff());

-- =========================================================================
-- Storage bucket for banner imagery
-- =========================================================================

insert into storage.buckets (id, name, public)
values ('banner-images', 'banner-images', true)
on conflict (id) do nothing;

drop policy if exists "vegear banner public read" on storage.objects;
create policy "vegear banner public read" on storage.objects
  for select using (bucket_id = 'banner-images');

drop policy if exists "vegear banner staff insert" on storage.objects;
create policy "vegear banner staff insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'banner-images' and public.is_staff());

drop policy if exists "vegear banner staff update" on storage.objects;
create policy "vegear banner staff update" on storage.objects
  for update to authenticated
  using (bucket_id = 'banner-images' and public.is_staff())
  with check (bucket_id = 'banner-images' and public.is_staff());

drop policy if exists "vegear banner staff delete" on storage.objects;
create policy "vegear banner staff delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'banner-images' and public.is_staff());

-- =========================================================================

-- ---------------------------------------------------------------------------
-- 0007_page_content.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0007 CMS pages (about / terms / privacy / refund)
-- Optional when using the JSON CMS fallback in site_settings.socials._cms.
-- Prefer applying 0006_cms.sql first.

create table if not exists public.content_pages (
  slug       text primary key check (slug in ('about','terms','privacy','refund')),
  title      text not null,
  body_html  text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.content_pages enable row level security;

drop policy if exists content_pages_public_read on public.content_pages;
create policy content_pages_public_read on public.content_pages
  for select using (true);

drop policy if exists content_pages_staff_write on public.content_pages;
create policy content_pages_staff_write on public.content_pages
  for all using (public.is_staff()) with check (public.is_staff());

drop trigger if exists trg_content_pages_touch on public.content_pages;
create trigger trg_content_pages_touch before update on public.content_pages
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 0008_banner_section.sql
-- ---------------------------------------------------------------------------
-- Rename homepage section type hero → banner
alter table public.homepage_sections
  drop constraint if exists homepage_sections_type_check;

update public.homepage_sections
set type = 'banner'
where type = 'hero';

alter table public.homepage_sections
  add constraint homepage_sections_type_check
  check (type in ('banner','categories','featured','reviews','promo','richtext'));

-- ---------------------------------------------------------------------------
-- 0009_product_sort.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0009 product catalog sort order
-- Lets admin drag-reorder products on the storefront / admin list.

alter table public.products
  add column if not exists sort int not null default 0;

create index if not exists products_sort_idx on public.products (sort, created_at desc);

-- Seed existing rows with a stable order from created_at (oldest first → lower sort).
with ordered as (
  select id, (row_number() over (order by created_at asc, id asc)) * 10 as next_sort
  from public.products
)
update public.products p
set sort = ordered.next_sort
from ordered
where p.id = ordered.id and p.sort = 0;

-- ---------------------------------------------------------------------------
-- 0010_product_size_chart.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0010 product size chart
-- Optional per-product size guide shown on the storefront when provided.
-- Shape: [{ "size": "M", "chest": "22", "length": "28" }, ...]
-- Null / empty array = no size chart UI.

alter table public.products
  add column if not exists size_chart jsonb default null;

comment on column public.products.size_chart is
  'Optional size guide rows: [{size, chest, length}, ...] in inches.';

-- Seed a default tee chart on existing active products that have none
update public.products
set size_chart = '[
  {"size":"M","chest":"22","length":"28"},
  {"size":"L","chest":"23","length":"29"},
  {"size":"XL","chest":"24.5","length":"30"},
  {"size":"2XL","chest":"26","length":"31"}
]'::jsonb
where size_chart is null
  and status = 'active'
  and coalesce(product_type, '') in ('tee', 't-shirt', 'tshirt', '');

-- ---------------------------------------------------------------------------
-- 0011_favicon.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0011 favicon
-- Optional browser tab icon, uploaded from Admin → Settings → Brand.

alter table public.site_settings
  add column if not exists favicon_path text;

comment on column public.site_settings.favicon_path is
  'Storage object path in the branding bucket for the site favicon.';

-- ---------------------------------------------------------------------------
-- 0012_promotion_cta.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0012 promotion CTA (link promo modal / strip to a product or URL)

alter table public.promotions
  add column if not exists cta_url text,
  add column if not exists cta_label text;

-- ---------------------------------------------------------------------------
-- 0013_audit_logs.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0013 audit logs (append-only admin / store activity)

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  actor_id uuid references auth.users (id) on delete set null,
  actor_email text,
  actor_role text,
  action text not null,
  entity text not null,
  entity_id text,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);

create index if not exists audit_logs_entity_created_at_idx
  on public.audit_logs (entity, created_at desc);

create index if not exists audit_logs_actor_created_at_idx
  on public.audit_logs (actor_id, created_at desc);

alter table public.audit_logs enable row level security;

-- Admins can read; writes go through the service-role client only.
drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs
  for select using (public.is_admin());

-- ---------------------------------------------------------------------------
-- 0014_promo_codes.sql
-- ---------------------------------------------------------------------------
-- VE-gear :: 0014 promo codes (checkout flat % off, excl. delivery)

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  percent numeric(5, 2) not null
    check (percent > 0 and percent <= 100),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint promo_codes_dates_check check (ends_at > starts_at)
);

create unique index if not exists promo_codes_code_upper_uidx
  on public.promo_codes (upper(code));

create index if not exists promo_codes_active_window_idx
  on public.promo_codes (active, starts_at, ends_at);

alter table public.promo_codes enable row level security;

-- Staff manage codes in admin; storefront validation uses service role.
drop policy if exists promo_codes_staff_read on public.promo_codes;
create policy promo_codes_staff_read on public.promo_codes
  for select using (public.is_staff());

drop policy if exists promo_codes_staff_write on public.promo_codes;
create policy promo_codes_staff_write on public.promo_codes
  for all using (public.is_staff()) with check (public.is_staff());

-- ---------------------------------------------------------------------------
-- 0015_email_smtp_settings.sql
-- ---------------------------------------------------------------------------
-- Private SMTP settings for order notification emails.
-- Intentionally NOT on site_settings (that table is publicly readable).

create table if not exists public.email_smtp_settings (
  id              int primary key default 1 check (id = 1),
  enabled         boolean not null default false,
  provider        text not null default 'gmail'
                    check (provider in ('gmail', 'smtp')),
  host            text,
  port            int not null default 587,
  secure          boolean not null default false, -- true = TLS on connect (465)
  username        text,
  password        text,
  from_name       text not null default 'VE Gear',
  from_email      text,
  notify_emails   text[] not null default '{}',
  updated_at      timestamptz not null default now()
);

insert into public.email_smtp_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.email_smtp_settings enable row level security;

drop policy if exists email_smtp_settings_admin_all on public.email_smtp_settings;
create policy email_smtp_settings_admin_all on public.email_smtp_settings
  for all using (public.is_admin()) with check (public.is_admin());

-- No public/anon read policy — only admins (and service role) can access.

-- ---------------------------------------------------------------------------
-- 0016_bkash_settings.sql
-- ---------------------------------------------------------------------------
-- Private bKash PGW settings (admin-only; not on public site_settings).
create table if not exists public.bkash_settings (
  id          int primary key default 1 check (id = 1),
  enabled     boolean not null default false,
  sandbox     boolean not null default true,
  username    text,
  password    text,
  app_key     text,
  app_secret  text,
  updated_at  timestamptz not null default now()
);

insert into public.bkash_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.bkash_settings enable row level security;

drop policy if exists bkash_settings_admin_all on public.bkash_settings;
create policy bkash_settings_admin_all on public.bkash_settings
  for all using (public.is_admin()) with check (public.is_admin());

-- Order payment tracking for COD + bKash
alter table public.orders
  add column if not exists payment_status text not null default 'unpaid';

alter table public.orders
  add column if not exists bkash_payment_id text;

alter table public.orders
  add column if not exists bkash_trx_id text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'orders_payment_status_check'
  ) then
    alter table public.orders
      add constraint orders_payment_status_check
      check (payment_status in ('unpaid', 'paid', 'failed'));
  end if;
end $$;

create index if not exists orders_bkash_payment_id_idx
  on public.orders (bkash_payment_id)
  where bkash_payment_id is not null;

-- place_order: accept payment_method; set payment_status unpaid
create or replace function public.place_order(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_order_number text;
  v_payment_method text;
  item jsonb;
begin
  if payload -> 'delivery' is null or payload -> 'items' is null or payload -> 'totals' is null then
    raise exception 'delivery, items and totals are required';
  end if;

  v_payment_method := lower(coalesce(nullif(payload ->> 'payment_method', ''), 'cod'));
  if v_payment_method not in ('cod', 'bkash') then
    v_payment_method := 'cod';
  end if;

  insert into public.orders (delivery, totals, notes, payment_method, payment_status)
  values (
    payload -> 'delivery',
    payload -> 'totals',
    nullif(payload ->> 'notes', ''),
    v_payment_method,
    'unpaid'
  )
  returning id, order_number into v_order_id, v_order_number;

  for item in select * from jsonb_array_elements(payload -> 'items') loop
    insert into public.order_items
      (order_id, product_id, variant_id, title, size, color, quantity, unit_price)
    values (
      v_order_id,
      nullif(item ->> 'product_id', '')::uuid,
      nullif(item ->> 'variant_id', '')::uuid,
      item ->> 'title',
      item ->> 'size',
      item ->> 'color',
      coalesce((item ->> 'quantity')::int, 1),
      coalesce((item ->> 'unit_price')::numeric, 0)
    );

    if nullif(item ->> 'variant_id', '') is not null then
      update public.product_variants
        set stock_quantity = greatest(0, stock_quantity - coalesce((item ->> 'quantity')::int, 1))
        where id = (item ->> 'variant_id')::uuid;
    end if;
  end loop;

  return jsonb_build_object('id', v_order_id, 'order_number', v_order_number);
end;
$$;

grant execute on function public.place_order(jsonb) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 0017_courier_integrations.sql
-- ---------------------------------------------------------------------------
-- Courier provider configuration, shipments, and webhook history.

create table if not exists public.courier_settings (
  provider         text primary key check (provider in ('pathao', 'steadfast', 'redx')),
  active           boolean not null default false,
  sandbox          boolean not null default false,
  client_id        text,
  client_secret    text,
  username         text,
  password         text,
  api_key          text,
  secret_key       text,
  access_token     text,
  pickup_store_id  text,
  webhook_secret   text,
  updated_at       timestamptz not null default now()
);

insert into public.courier_settings (provider, sandbox)
values
  ('pathao', true),
  ('steadfast', false),
  ('redx', true)
on conflict (provider) do nothing;

create unique index if not exists courier_settings_one_active_idx
  on public.courier_settings ((active))
  where active;

create table if not exists public.order_shipments (
  id                  uuid primary key default gen_random_uuid(),
  order_id            uuid not null unique references public.orders (id) on delete restrict,
  provider            text not null check (provider in ('pathao', 'steadfast', 'redx')),
  sync_state          text not null default 'creating'
                        check (sync_state in ('creating', 'synced', 'failed', 'unknown')),
  external_id         text,
  tracking_code       text,
  courier_status      text,
  status_message      text,
  delivery_area_id    text,
  delivery_area_name  text,
  parcel_weight       numeric(8,3),
  request_payload     jsonb,
  response_payload    jsonb,
  last_event_at       timestamptz,
  synced_at           timestamptz,
  created_by          uuid references public.profiles (id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create unique index if not exists order_shipments_external_id_idx
  on public.order_shipments (provider, external_id)
  where external_id is not null;
create unique index if not exists order_shipments_tracking_code_idx
  on public.order_shipments (provider, tracking_code)
  where tracking_code is not null;
create index if not exists order_shipments_provider_status_idx
  on public.order_shipments (provider, courier_status);

create table if not exists public.courier_events (
  id                uuid primary key default gen_random_uuid(),
  shipment_id       uuid not null references public.order_shipments (id) on delete cascade,
  provider          text not null check (provider in ('pathao', 'steadfast', 'redx')),
  event_key         text not null,
  event_name        text not null,
  courier_status    text,
  message           text,
  provider_time     timestamptz,
  payload           jsonb not null default '{}'::jsonb,
  created_at        timestamptz not null default now(),
  unique (provider, event_key)
);

create index if not exists courier_events_shipment_created_idx
  on public.courier_events (shipment_id, created_at desc);

drop trigger if exists trg_touch_courier_settings on public.courier_settings;
create trigger trg_touch_courier_settings
  before update on public.courier_settings
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_order_shipments on public.order_shipments;
create trigger trg_touch_order_shipments
  before update on public.order_shipments
  for each row execute function public.touch_updated_at();

alter table public.courier_settings enable row level security;
alter table public.order_shipments enable row level security;
alter table public.courier_events enable row level security;

drop policy if exists courier_settings_admin_all on public.courier_settings;
create policy courier_settings_admin_all on public.courier_settings
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists order_shipments_staff_read on public.order_shipments;
create policy order_shipments_staff_read on public.order_shipments
  for select using (public.is_staff());
drop policy if exists order_shipments_staff_insert on public.order_shipments;
create policy order_shipments_staff_insert on public.order_shipments
  for insert with check (public.is_staff());
drop policy if exists order_shipments_staff_update on public.order_shipments;
create policy order_shipments_staff_update on public.order_shipments
  for update using (public.is_staff()) with check (public.is_staff());

drop policy if exists courier_events_staff_read on public.courier_events;
create policy courier_events_staff_read on public.courier_events
  for select using (public.is_staff());

create or replace function public.save_courier_settings(
  p_settings jsonb,
  p_active_provider text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  item_provider text;
begin
  if not public.is_admin() then
    raise exception 'permission denied';
  end if;
  if p_active_provider is not null
     and p_active_provider not in ('pathao', 'steadfast', 'redx') then
    raise exception 'invalid courier provider';
  end if;

  update public.courier_settings set active = false where active;

  for item in select value from jsonb_array_elements(p_settings)
  loop
    item_provider := item ->> 'provider';
    if item_provider not in ('pathao', 'steadfast', 'redx') then
      raise exception 'invalid courier provider';
    end if;

    insert into public.courier_settings (
      provider, active, sandbox, client_id, client_secret, username, password,
      api_key, secret_key, access_token, pickup_store_id, webhook_secret,
      updated_at
    ) values (
      item_provider,
      item_provider = p_active_provider,
      coalesce((item ->> 'sandbox')::boolean, false),
      nullif(item ->> 'client_id', ''),
      nullif(item ->> 'client_secret', ''),
      nullif(item ->> 'username', ''),
      nullif(item ->> 'password', ''),
      nullif(item ->> 'api_key', ''),
      nullif(item ->> 'secret_key', ''),
      nullif(item ->> 'access_token', ''),
      nullif(item ->> 'pickup_store_id', ''),
      nullif(item ->> 'webhook_secret', ''),
      now()
    )
    on conflict (provider) do update set
      active = excluded.active,
      sandbox = excluded.sandbox,
      client_id = excluded.client_id,
      client_secret = excluded.client_secret,
      username = excluded.username,
      password = excluded.password,
      api_key = excluded.api_key,
      secret_key = excluded.secret_key,
      access_token = excluded.access_token,
      pickup_store_id = excluded.pickup_store_id,
      webhook_secret = excluded.webhook_secret,
      updated_at = now();
  end loop;
end;
$$;

revoke all on function public.save_courier_settings(jsonb, text) from public;
grant execute on function public.save_courier_settings(jsonb, text) to authenticated;

-- Lock-check, restock, and delete in one transaction. The shipment foreign key
-- remains the final guard if a courier sync races with this function.
create or replace function public.delete_orders_safely(p_order_ids uuid[])
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_orders jsonb;
begin
  if not public.is_staff() then
    raise exception 'permission denied';
  end if;

  perform 1
  from public.orders
  where id = any(p_order_ids)
  for update;

  if exists (
    select 1
    from public.order_shipments
    where order_id = any(p_order_ids)
  ) then
    raise exception 'courier-synced orders cannot be deleted';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', id,
        'order_number', order_number,
        'status', status
      )
      order by created_at
    ),
    '[]'::jsonb
  )
  into v_orders
  from public.orders
  where id = any(p_order_ids);

  with quantities as (
    select oi.variant_id, sum(oi.quantity)::int as quantity
    from public.order_items oi
    join public.orders o on o.id = oi.order_id
    where o.id = any(p_order_ids)
      and o.status in ('pending', 'confirmed', 'processing')
      and oi.variant_id is not null
    group by oi.variant_id
  )
  update public.product_variants variant
  set stock_quantity = greatest(0, variant.stock_quantity + quantities.quantity),
      updated_at = now()
  from quantities
  where variant.id = quantities.variant_id;

  delete from public.orders where id = any(p_order_ids);
  return v_orders;
end;
$$;

revoke all on function public.delete_orders_safely(uuid[]) from public;
grant execute on function public.delete_orders_safely(uuid[]) to authenticated;

create or replace function public.delete_customers_safely(p_customer_ids uuid[])
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customers jsonb;
  v_order_ids uuid[];
begin
  if not public.is_staff() then
    raise exception 'permission denied';
  end if;

  perform 1
  from public.customers
  where id = any(p_customer_ids)
  for update;

  select coalesce(
    jsonb_agg(jsonb_build_object('id', id, 'name', name, 'phone', phone)),
    '[]'::jsonb
  )
  into v_customers
  from public.customers
  where id = any(p_customer_ids);

  select coalesce(array_agg(id), array[]::uuid[])
  into v_order_ids
  from public.orders
  where customer_id = any(p_customer_ids);

  if cardinality(v_order_ids) > 0 then
    perform public.delete_orders_safely(v_order_ids);
  end if;

  delete from public.customers where id = any(p_customer_ids);
  return v_customers;
end;
$$;

revoke all on function public.delete_customers_safely(uuid[]) from public;
grant execute on function public.delete_customers_safely(uuid[]) to authenticated;

create or replace function public.cancel_order_safely(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status public.order_status;
begin
  if not public.is_staff() then
    raise exception 'permission denied';
  end if;

  select status into v_status
  from public.orders
  where id = p_order_id
  for update;

  if v_status is null then
    raise exception 'order not found';
  end if;
  if v_status in ('delivered', 'cancelled') then
    raise exception 'order cannot be cancelled';
  end if;
  if exists (
    select 1 from public.order_shipments where order_id = p_order_id
  ) then
    raise exception 'courier-synced orders cannot be cancelled';
  end if;

  with quantities as (
    select variant_id, sum(quantity)::int as quantity
    from public.order_items
    where order_id = p_order_id and variant_id is not null
    group by variant_id
  )
  update public.product_variants variant
  set stock_quantity = greatest(0, variant.stock_quantity + quantities.quantity),
      updated_at = now()
  from quantities
  where variant.id = quantities.variant_id;

  update public.orders
  set status = 'cancelled', updated_at = now()
  where id = p_order_id;
end;
$$;

revoke all on function public.cancel_order_safely(uuid) from public;
grant execute on function public.cancel_order_safely(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 0018_abandoned_gateway_orders.sql
-- ---------------------------------------------------------------------------
-- Remove incomplete gateway orders and return reserved stock.

create or replace function public.delete_unpaid_gateway_order(p_order_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
begin
  select id into v_order_id
  from public.orders
  where id = p_order_id
    and payment_method <> 'cod'
    and payment_status <> 'paid'
  for update;

  if v_order_id is null then
    return false;
  end if;
  if exists (
    select 1 from public.order_shipments where order_id = p_order_id
  ) then
    return false;
  end if;

  with quantities as (
    select variant_id, sum(quantity)::int as quantity
    from public.order_items
    where order_id = p_order_id and variant_id is not null
    group by variant_id
  )
  update public.product_variants variant
  set stock_quantity = greatest(0, variant.stock_quantity + quantities.quantity),
      updated_at = now()
  from quantities
  where variant.id = quantities.variant_id;

  delete from public.orders where id = p_order_id;
  return true;
end;
$$;

revoke all on function public.delete_unpaid_gateway_order(uuid) from public;
grant execute on function public.delete_unpaid_gateway_order(uuid) to service_role;

create or replace function public.cleanup_abandoned_gateway_orders(
  p_cutoff timestamptz default (now() - interval '1 hour')
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate record;
  deleted_numbers text[] := array[]::text[];
begin
  for candidate in
    select id, order_number
    from public.orders
    where payment_method <> 'cod'
      and payment_status = 'unpaid'
      and created_at < p_cutoff
    order by created_at
    for update skip locked
  loop
    if public.delete_unpaid_gateway_order(candidate.id) then
      deleted_numbers := array_append(deleted_numbers, candidate.order_number);
    end if;
  end loop;

  return jsonb_build_object(
    'count', cardinality(deleted_numbers),
    'order_numbers', to_jsonb(deleted_numbers)
  );
end;
$$;

revoke all on function public.cleanup_abandoned_gateway_orders(timestamptz) from public;
grant execute on function public.cleanup_abandoned_gateway_orders(timestamptz) to service_role;

create extension if not exists pg_cron with schema pg_catalog;

do $$
declare
  existing_job record;
begin
  for existing_job in
    select jobid from cron.job where jobname = 'cleanup-abandoned-gateway-orders'
  loop
    perform cron.unschedule(existing_job.jobid);
  end loop;

  perform cron.schedule(
    'cleanup-abandoned-gateway-orders',
    '*/15 * * * *',
    $job$select public.cleanup_abandoned_gateway_orders(now() - interval '1 hour');$job$
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- 0047_sms_otp_settings.sql
-- ---------------------------------------------------------------------------
-- Khudebarta SMS gateway configuration and checkout OTP verification.

create table if not exists public.sms_settings (
  id           int primary key default 1 check (id = 1),
  enabled      boolean not null default false,
  sender_id    text,
  api_key      text,
  secret_key   text,
  checkout_otp boolean not null default false,
  updated_at   timestamptz not null default now()
);

insert into public.sms_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.sms_settings enable row level security;

drop policy if exists sms_settings_admin_all on public.sms_settings;
create policy sms_settings_admin_all on public.sms_settings
  for all using (public.is_admin()) with check (public.is_admin());

drop trigger if exists trg_touch_sms_settings on public.sms_settings;
create trigger trg_touch_sms_settings
  before update on public.sms_settings
  for each row execute function public.touch_updated_at();

create table if not exists public.sms_otps (
  id          uuid primary key default gen_random_uuid(),
  phone       text not null,
  code_hash   text not null,
  salt        text not null,
  expires_at  timestamptz not null,
  attempts    int not null default 0,
  used        boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists sms_otps_phone_created_idx
  on public.sms_otps (phone, created_at desc);

alter table public.sms_otps enable row level security;

-- Neutral defaults for new client stores. Client initialization can replace them.
alter table public.orders
  alter column order_number set default ('ORD-' || nextval('order_number_seq')::text);
alter table public.site_settings
  alter column store_name set default 'Store';
alter table public.email_smtp_settings
  alter column from_name set default 'Store';

update public.site_settings
set store_name = 'Store', contact_email = null
where id = 1;

update public.email_smtp_settings
set from_name = 'Store'
where id = 1;

commit;
